analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

include: package:effective_dart/analysis_options.1.3.0.yaml
linter:
  rules:
    prefer_relative_imports: false
    public_member_api_docs: false
    one_member_abstracts: false
