# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
    if latest_release.nil?
      puts "No latest release found"
    else
      increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
    end
  end
  lane :build do
    gradle(task: "clean")
    gradle(task: "assemble", build_type: "Release")
  end
  desc "Firebase app distribution"
  lane :distribute do
    puts ENV["TESTERS"]
    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        testers_file: ENV["TESTERS"],
        service_credentials_file: ENV["GOOGLE_APPLICATION_CREDENTIALS"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        release_notes: ENV["RELEASE_NOTE"])
  end
end
